"""init

Revision ID: 49ee16e06d99
Revises: 6add1b018170
Create Date: 2026-01-24 19:22:01.813675

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '49ee16e06d99'
down_revision: Union[str, Sequence[str], None] = '6add1b018170'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bosses',
    sa.Column('name', postgresql.CITEXT(), nullable=False),
    sa.Column('ehb', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('ehb > 0', name=op.f('bosses_boss_ehb_gt_0_check')),
    sa.PrimaryKeyConstraint('id', name=op.f('bosses_pkey'))
    )
    op.create_index(op.f('ix_bosses_created_at'), 'bosses', ['created_at'], unique=False)
    op.create_index(op.f('ix_bosses_name'), 'bosses', ['name'], unique=True)
    op.create_table('events',
    sa.Column('name', postgresql.CITEXT(), nullable=False),
    sa.Column('starts_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ends_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('events_pkey'))
    )
    op.create_index(op.f('ix_events_created_at'), 'events', ['created_at'], unique=False)
    op.create_index(op.f('ix_events_ends_at'), 'events', ['ends_at'], unique=False)
    op.create_index(op.f('ix_events_name'), 'events', ['name'], unique=True)
    op.create_index(op.f('ix_events_starts_at'), 'events', ['starts_at'], unique=False)
    op.create_table('items',
    sa.Column('name', postgresql.CITEXT(), nullable=False),
    sa.Column('drop_rate', sa.Integer(), nullable=False),
    sa.Column('point_value', sa.Integer(), nullable=False),
    sa.Column('boss_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['boss_id'], ['bosses.id'], name=op.f('items_boss_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('items_pkey')),
    sa.UniqueConstraint('boss_id', 'name', name=op.f('items_boss_id_name_key'))
    )
    op.create_index(op.f('ix_items_boss_id'), 'items', ['boss_id'], unique=False)
    op.create_index(op.f('ix_items_created_at'), 'items', ['created_at'], unique=False)
    op.create_index(op.f('ix_items_name'), 'items', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_items_name'), table_name='items')
    op.drop_index(op.f('ix_items_created_at'), table_name='items')
    op.drop_index(op.f('ix_items_boss_id'), table_name='items')
    op.drop_table('items')
    op.drop_index(op.f('ix_events_starts_at'), table_name='events')
    op.drop_index(op.f('ix_events_name'), table_name='events')
    op.drop_index(op.f('ix_events_ends_at'), table_name='events')
    op.drop_index(op.f('ix_events_created_at'), table_name='events')
    op.drop_table('events')
    op.drop_index(op.f('ix_bosses_name'), table_name='bosses')
    op.drop_index(op.f('ix_bosses_created_at'), table_name='bosses')
    op.drop_table('bosses')
    # ### end Alembic commands ###
