"""init

Revision ID: ed802d6f8ea8
Revises: 
Create Date: 2026-01-13 21:08:23.626099

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'ed802d6f8ea8'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bosses',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('ehb', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('bosses_pkey')),
    sa.UniqueConstraint('name', name=op.f('bosses_name_key'))
    )
    op.create_index(op.f('ix_bosses_created_at'), 'bosses', ['created_at'], unique=False)
    op.create_table('events',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('type', sa.Enum('TRADITIONAL', 'LEVELS', name='event_type'), nullable=False),
    sa.Column('starts_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ends_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('ends_at > starts_at', name=op.f('events_event_schedule_valid_check')),
    sa.PrimaryKeyConstraint('id', name=op.f('events_pkey'))
    )
    op.create_index(op.f('ix_events_created_at'), 'events', ['created_at'], unique=False)
    op.create_index(op.f('ix_events_ends_at'), 'events', ['ends_at'], unique=False)
    op.create_index(op.f('ix_events_starts_at'), 'events', ['starts_at'], unique=False)
    op.create_index(op.f('ix_events_type'), 'events', ['type'], unique=False)
    op.create_table('boards',
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('rows', sa.Integer(), nullable=False),
    sa.Column('cols', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], name=op.f('boards_event_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('boards_pkey')),
    sa.UniqueConstraint('event_id', name=op.f('boards_event_id_key'))
    )
    op.create_index(op.f('ix_boards_created_at'), 'boards', ['created_at'], unique=False)
    op.create_index(op.f('ix_boards_event_id'), 'boards', ['event_id'], unique=False)
    op.create_table('items',
    sa.Column('boss_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('point_value', sa.Integer(), nullable=False),
    sa.Column('drop_rate', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['boss_id'], ['bosses.id'], name=op.f('items_boss_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('items_pkey')),
    sa.UniqueConstraint('boss_id', 'name', name=op.f('items_boss_id_name_key'))
    )
    op.create_index(op.f('ix_items_boss_id'), 'items', ['boss_id'], unique=False)
    op.create_index(op.f('ix_items_created_at'), 'items', ['created_at'], unique=False)
    op.create_table('tile',
    sa.Column('board_id', sa.Integer(), nullable=False),
    sa.Column('row_idx', sa.Integer(), nullable=False),
    sa.Column('col_idx', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('tile_type', sa.Enum('KC', 'UNIQUE', 'POINTS', name='tile_type'), nullable=False),
    sa.Column('target_value', sa.Integer(), nullable=False),
    sa.Column('reward_points', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['board_id'], ['boards.id'], name=op.f('tile_board_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('tile_pkey')),
    sa.UniqueConstraint('board_id', 'row_idx', 'col_idx', name=op.f('tile_board_id_row_idx_col_idx_key'))
    )
    op.create_index(op.f('ix_tile_board_id'), 'tile', ['board_id'], unique=False)
    op.create_index(op.f('ix_tile_created_at'), 'tile', ['created_at'], unique=False)
    op.create_index(op.f('ix_tile_tile_type'), 'tile', ['tile_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tile_tile_type'), table_name='tile')
    op.drop_index(op.f('ix_tile_created_at'), table_name='tile')
    op.drop_index(op.f('ix_tile_board_id'), table_name='tile')
    op.drop_table('tile')
    op.drop_index(op.f('ix_items_created_at'), table_name='items')
    op.drop_index(op.f('ix_items_boss_id'), table_name='items')
    op.drop_table('items')
    op.drop_index(op.f('ix_boards_event_id'), table_name='boards')
    op.drop_index(op.f('ix_boards_created_at'), table_name='boards')
    op.drop_table('boards')
    op.drop_index(op.f('ix_events_type'), table_name='events')
    op.drop_index(op.f('ix_events_starts_at'), table_name='events')
    op.drop_index(op.f('ix_events_ends_at'), table_name='events')
    op.drop_index(op.f('ix_events_created_at'), table_name='events')
    op.drop_table('events')
    op.drop_index(op.f('ix_bosses_created_at'), table_name='bosses')
    op.drop_table('bosses')
    # ### end Alembic commands ###
